### ISSUE TITLE
[IT Nº1] Diseño

### ISSUE THREAD

**Issue by AgustinESI** [AgustinESI/ISOFT2-2022-C02#3]
Implementación de la fase de diseño

**Comment by Enriquesmo** [comment]
Diseño de la primera iteración realizado. Se ha realizado a destiempo con relación a la planificación establecida debido a problemas personales. Adjunto enlace de progreso realizado:
https://github.com/AgustinESI/ISOFT2-2022-C02/wiki/Iteraci%C3%B3n-1#diagrama-de-clases
